import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: {
        absolute: "",
        default: "Martin",
        template: "%s | Martin"
    },
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className='bg-blue-300'><p>Header</p></header>
        {children}
        <footer className='bg-gray-700 p-[1rem]'><p>Footer</p></footer>
        </body>
        </html>
    );
}